name: 'AdaCGP'
hyperparams:
  P: 3
  gamma: 1.75
  lambda: 0.99
  nu: 0.005
  w_stepsize: 0.001
  h_stepsize: 0.001
  psi_stepsize: 1e-5
  use_eig_stepsize: false
  epsilon: 1e-3
  ma_alpha: 0.005
  use_path_1: true
  instant_h: true
  patience: 10000
  burn_in_debiasing: 250
  min_delta_percent: 0.01
  use_armijo: false
  use_armijo_w: false
  use_armijo_h: false
  warm_up_steps: 0
  alternate: false
  alternate_mod: 2
  monitor_debiasing: 'pred_error_recursive_moving_average_h'
  mus:
    - 0.1
    - 0.1
    - 0.1