name: 'AdaCGP'
hyperparams:
  P: 3
  gamma: 0.1
  w_stepsize: 1e-3
  h_stepsize: 1e-4
  psi_stepsize: 1e-5
  epsilon: 1e-2
  lambda: 0.99
  nu: 0.01
  ma_alpha: 0.005
  use_path_1: false
  instant_h: true
  patience: 50
  use_armijo: false
  warm_up_steps: 0
  alternate: false
  alternate_mod: 2
  mus: [0.1, 0.1, 0.1]