seed: 42

hydra:
  mode: MULTIRUN
  sweep:
    dir: logs/${model.name}/${data.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: graph_${graph.graph_type}/N_${data.N}/seed_${seed}

  sweeper:
    params:
      seed: 42
      data.N: 25, 100, 500, 1000
      graph: random, kr, sbm, er, pl
    
  launcher:
    n_jobs: 5

defaults:
  - _self_
  - data: cgp
  - model: adacgp
  - graph: kr
  - override hydra/sweeper: basic
  - override hydra/launcher: joblib
