hydra:
  mode: MULTIRUN
  sweep:
    dir: logs/${model.name}/${data.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: graph_${graph.graph_type}/N_${data.N}/alpha_${model.hyperparams.alpha}/seed_${seed}

  sweeper:
    sampler:
      _target_: optuna.samplers.GridSampler
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    direction: minimize
    study_name: GLasso
    n_jobs: 4
    n_trials: 1000
  
    params:
      seed: 42
      graph: choice(random, kr, sbm, er)
      data.N: choice(50)
      model.hyperparams.alpha: choice(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0)

device: 'cpu'
seed: 42

defaults:
  - _self_
  - data: cgp
  - model: glasso
  - graph: kr
  - override hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: grid
  - override hydra/launcher: joblib
