data:
  N: 100
  P: 3
  process_length: 5000
  burn_in: 1000
  noise_factor: 1
  graph_cfg:
    graph_type: "SBM"

optimization:
  gamma: 0.1
  w_stepsize: 1e-3
  h_stepsize: 1e-4
  psi_stepsize: 1e-5
  epsilon: 1e-2
  lambda: 0.99
  nu: 0.01
  ma_alpha: 0.005
  use_path_1: false
  instant_h: true
  patience: 50
  use_data_adaptive_step: true
  use_armijo: false
  warm_up_steps: 0
  alternate: false
  alternate_mod: 2
  mus: [0.1, 0.1, 0.1]

device: "cuda"