seed: 42

hydra:
  mode: MULTIRUN
  sweep:
    dir: logs/${model.name}/${data.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: graph_${graph.graph_type}/N_${data.N}/alternate_${model.hyperparams.alternate}/use_path_1_${model.hyperparams.use_path_1}/gamma_${model.hyperparams.gamma}/lambda_${model.hyperparams.lambda}/nu_${model.hyperparams.nu}/mus_${model.hyperparams.mus.0}_${model.hyperparams.mus.1}_${model.hyperparams.mus.2}/seed_${seed}

  sweeper:
    sampler:
      _target_: optuna.samplers.RandomSampler
      seed: 42
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    direction: minimize
    study_name: AdaCGP
    n_trials: 50000
    n_jobs: 30
  
    params:
      seed: 42
      graph: choice(random, kr, sbm, er)
      data.N: choice(50)
      model.hyperparams.use_path_1: choice(true, false)
      model.hyperparams.alternate: choice(true, false)
      model.hyperparams.gamma: choice(0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95, 1.0, 1.05, 1.1, 1.15, 1.2, 1.25, 1.3, 1.35, 1.4, 1.45, 1.5, 1.55, 1.6, 1.65, 1.7, 1.75, 1.8, 1.85, 1.9, 1.95, 2.0)
      model.hyperparams.lambda: choice(0.80, 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.90, 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99)
      model.hyperparams.nu: choice(0.005)
      model.hyperparams.mus.0: interval(0.001, 1)
      model.hyperparams.mus.1: interval(0.001, 1)
      model.hyperparams.mus.2: interval(0.001, 1)

device: cpu

defaults:
  - _self_
  - data: cgp
  - model: adacgp
  - graph: kr
  - override hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: random
  - override hydra/launcher: ray
